import React, { useState, useEffect } from 'react';
import { AlertOctagon, Cpu, ArrowUpRight, Database, GitCommit, CheckCircle } from 'lucide-react';
import { 
  AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, 
  BarChart, Bar, LineChart, Line, Legend 
} from 'recharts';

// Logs with distinct "Badge" styling
const logs = [
  { id: 1, type: "INF", msg: "RUL Prediction: 120h", time: "10:42:15" },
  { id: 2, type: "SYS", msg: "TP2 Sensor Normalized", time: "10:42:05" },
  { id: 4, type: "INF", msg: "Batch Processed (180)", time: "10:41:45" },
];

// --- Types for Static Analysis ---
interface ModelMetrics {
  MAE_Train: number;
  MAE_Test: number;
}

interface StaticData {
  metrics: Record<string, ModelMetrics>;
  train_data: any[];
  test_data: any[];
}

interface RulBin {
  bin: string;
  count: number;
}

export const Overview = () => {
  const [loading, setLoading] = useState(true);
  const [staticData, setStaticData] = useState<StaticData | null>(null);
  
  // Side panel states
  const [rulDist, setRulDist] = useState<RulBin[] | null>(null);
  const [rulSeries, setRulSeries] = useState<any>(null);
  const [seriesLoading, setSeriesLoading] = useState(false);

  // 1. Load Static Model Performance (Generated by Python)
  useEffect(() => {
    const fetchAnalysis = async () => {
      setLoading(true);
      try {
        const res = await fetch('/static_performance.json');
        if (res.ok) {
          const json = await res.json();
          setStaticData(json);
          // Attempt to build distribution from test data immediately if API fails
          generateDistributionFallback(json.test_data); 
        } else {
          console.error('Failed to fetch static performance');
        }
      } catch (e) {
        console.error('Error fetching analysis', e);
      } finally {
        setLoading(false);
      }
    };

    fetchAnalysis();
    fetchRulSeries(); // Load the side panel series
  }, []);

  // Helper: Client-side histogram fallback
  const generateDistributionFallback = (testData: any[]) => {
    if (!testData || testData.length === 0) return;
    
    try {
      // Fixed bins between 0 and 120 (RUL cap) to match preprocessing
      const vals = testData.map((d: any) => d.Actual);
      const nBins = 12; // 10h per bin
      const min = 0;
      const max = 120;
      const width = (max - min) / nBins;

      const bins = new Array(nBins).fill(0).map((_, i) => ({ 
        bin: `${Math.round(min + i * width)}-${Math.round(min + (i+1)*width)}`, 
        count: 0 
      }));

      vals.forEach((v: number) => {
        const clamped = Math.max(min, Math.min(max, v));
        const idx = Math.min(nBins - 1, Math.floor((clamped - min) / width));
        bins[idx].count += 1;
      });
      setRulDist(bins);
    } catch (e) {
      console.error("Dist generation error", e);
    }
  };

  const openDriftReport = () => {
    window.open('http://localhost:8000/static/data_drift_report.html', '_blank');
  };

  const fetchRulSeries = async () => {
    setSeriesLoading(true);
    try {
      // Logic for side panel small chart
      const res = await fetch('/api/rul-series?limit=200'); 
      if (res.ok) {
        const json = await res.json();
        setRulSeries(json.data || []);
      }
    } catch (e) {
      // console.error('Error fetching RUL series', e);
    } finally {
      setSeriesLoading(false);
    }
  };

  // Helper: downsample a time-series array to at most `maxPoints` uniformly
  const downsample = (arr: any[] | undefined | null, maxPoints = 800) => {
    if (!arr || arr.length <= maxPoints) return arr || [];
    const step = Math.ceil(arr.length / maxPoints);
    const out: any[] = [];
    for (let i = 0; i < arr.length; i += step) {
      out.push(arr[i]);
    }
    return out;
  };

  return (
    <div className="space-y-8 animate-fade-in">
      
      {/* 1. Alert Banner (Preserved) */}
      <div className="relative overflow-hidden rounded-2xl bg-gradient-to-r from-red-500/10 via-orange-500/5 to-transparent border border-red-500/20 p-6">
        <div className="absolute top-0 right-0 p-3 opacity-10">
            <AlertOctagon size={120} />
        </div>
        <div className="relative z-10 flex justify-between items-start">
            <div>
                <h3 className="text-xl font-bold text-white flex items-center gap-2">
                    <span className="text-red-400">●</span> Drift Threshold Exceeded
                </h3>
                <p className="text-slate-400 mt-2 max-w-2xl text-sm">
                    Concept drift detected in incoming sensor streams. The statistical properties of the target variable have shifted significantly (Score: 1.0).
                </p>
            </div>
            <button 
                onClick={openDriftReport}
                className="bg-white/5 hover:bg-white/10 text-white border border-white/10 px-6 py-2 rounded-lg font-medium backdrop-blur-sm transition-all flex items-center gap-2 text-sm"
            >
                Analyze Drift Report 
            </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* 2. Main Card - Static Model Performance (Updated) */}
        <div className="lg:col-span-8 space-y-6">
            
            {/* A. Metrics Grid */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                {staticData && Object.entries(staticData.metrics).map(([model, metrics]) => (
                  <div key={model} className="bg-slate-800/40 p-4 rounded-xl border border-white/5 backdrop-blur-md relative overflow-hidden">
                    {model === 'LSTM' && (
                        <div className="absolute top-0 right-0 bg-blue-500/20 text-blue-300 text-[10px] font-bold px-2 py-1 rounded-bl-lg">
                            CHAMPION
                        </div>
                    )}
                    <h3 className="font-bold text-slate-200 text-sm">{model} Model</h3>
                    <div className="grid grid-cols-2 gap-4 mt-3">
                      <div>
                        <p className="text-[10px] text-slate-500 uppercase">Train MAE</p>
                        <p className="text-lg font-mono text-white">{metrics.MAE_Train}h</p>
                      </div>
                      <div>
                        <p className="text-[10px] text-slate-500 uppercase">Test MAE</p>
                        <p className={`text-lg font-mono ${metrics.MAE_Test < 10 ? 'text-green-400' : 'text-yellow-400'}`}>
                          {metrics.MAE_Test}h
                        </p>
                      </div>
                    </div>
                  </div>
                ))}
            </div>

            {/* B. Charts Container */}
            <div className="bg-slate-800/40 backdrop-blur-md p-6 rounded-2xl border border-white/5 shadow-xl h-[500px] overflow-y-auto custom-scrollbar">
                
                {/* Chart 1: Training Fit */}
                <div className="mb-8">
                    <div className="flex items-center gap-2 mb-4">
                        <Database size={16} className="text-blue-400"/>
                        <div>
                            <h3 className="font-bold text-white text-sm">Training Phase Performance</h3>
                            <p className="text-xs text-slate-500">Learning capability on historical data (75% split)</p>
                        </div>
                    </div>
                    <div className="h-[250px] w-full bg-slate-900/30 rounded-lg border border-white/5 p-2">
                        {loading ? <div className="h-full flex items-center justify-center text-slate-500">Loading...</div> : (
                            <ResponsiveContainer width="100%" height="100%">
                                <LineChart data={downsample(staticData?.train_data, 800)}>
                                    <CartesianGrid strokeDasharray="3 3" stroke="#334155" vertical={false} opacity={0.4} />
                                    <XAxis dataKey="time" hide />
                                    <YAxis stroke="#64748b" fontSize={10} width={30} domain={[0, 120]} />
                                    <Tooltip contentStyle={{ backgroundColor: '#0f172a', borderColor: '#334155', fontSize: '12px' }} />
                                    <Legend verticalAlign="top" height={36} iconSize={8} wrapperStyle={{fontSize: '10px'}}/>
                                        <Line type="monotone" dataKey="Actual" stroke="#64748b" strokeWidth={1} dot={false} />
                                        <Line type="monotone" dataKey="GRU" stroke="#3b82f6" strokeWidth={2} dot={false} strokeOpacity={0.8} />
                                        <Line type="monotone" dataKey="CNN" stroke="#ec4899" strokeWidth={1} dot={false} strokeOpacity={0.6} />
                                        <Line type="monotone" dataKey="LSTM" stroke="#10b981" strokeWidth={1} dot={false} strokeOpacity={0.7} strokeDasharray="4 4" />
                                </LineChart>
                            </ResponsiveContainer>
                        )}
                    </div>
                </div>

                {/* Chart 2: Test Generalization */}
                <div>
                    <div className="flex items-center gap-2 mb-4">
                        <GitCommit size={16} className="text-green-400"/>
                        <div>
                            <h3 className="font-bold text-white text-sm">Test Set Generalization</h3>
                            <p className="text-xs text-slate-500">Performance on unseen data (25% split)</p>
                        </div>
                    </div>
                    <div className="h-[250px] w-full bg-slate-900/30 rounded-lg border border-white/5 p-2">
                        {loading ? <div className="h-full flex items-center justify-center text-slate-500">Loading...</div> : (
                            <ResponsiveContainer width="100%" height="100%">
                                <LineChart data={downsample(staticData?.test_data, 800)}>
                                    <CartesianGrid strokeDasharray="3 3" stroke="#334155" vertical={false} opacity={0.4} />
                                    <XAxis dataKey="time" hide />
                                    <YAxis stroke="#64748b" fontSize={10} width={30} domain={[0, 120]} />
                                    <Tooltip contentStyle={{ backgroundColor: '#0f172a', borderColor: '#334155', fontSize: '12px' }} />
                                    <Legend verticalAlign="top" height={36} iconSize={8} wrapperStyle={{fontSize: '10px'}}/>
                                        <Line type="monotone" dataKey="Actual" stroke="#64748b" strokeWidth={2} dot={false} name="Actual RUL"/>
                                        <Line type="monotone" dataKey="GRU" stroke="#3b82f6" strokeWidth={2} dot={false} name="Predicted (GRU)" />
                                        <Line type="monotone" dataKey="CNN" stroke="#ef4444" strokeWidth={1} dot={false} name="Predicted (CNN)" />
                                        <Line type="monotone" dataKey="LSTM" stroke="#10b981" strokeWidth={1} dot={false} strokeDasharray="4 4" name="Predicted (LSTM)" />
                                </LineChart>
                            </ResponsiveContainer>
                        )}
                    </div>
                    <p className="text-[10px] text-center text-slate-500 mt-2">
                        * The Blue line (GRU) tracking the Gray line (Actual) indicates high model fidelity on unseen data.
                    </p>
                </div>
            </div>
        </div>

        {/* 3. Side Panel (Preserved) */}
        <div className="lg:col-span-4 flex flex-col gap-6">
            {/* KPI Card */}
            <div className="bg-gradient-to-br from-indigo-500/20 to-purple-500/20 p-6 rounded-2xl border border-indigo-500/20 relative overflow-hidden group">
                <div className="absolute right-0 top-0 p-4 opacity-0 group-hover:opacity-20 transition-opacity">
                    <ArrowUpRight size={48} className="text-white" />
                </div>
                <h4 className="text-indigo-300 text-sm font-medium uppercase tracking-wider">Confidence</h4>
                <div className="text-4xl font-bold text-white mt-2 font-mono">98.2<span className="text-lg text-indigo-300">%</span></div>
                <p className="text-xs text-indigo-200/60 mt-2">Running on GPU-01</p>
            </div>

            {/* Log Panel */}
            <div className="bg-slate-800/40 backdrop-blur-md p-0 rounded-2xl border border-white/5 flex-1 overflow-hidden flex flex-col min-h-[300px]">
                <div className="p-4 border-b border-white/5 bg-slate-900/50 flex justify-between items-center">
                    <h3 className="font-bold text-white text-sm">System Events</h3>
                    <Cpu size={14} className="text-slate-500" />
                </div>
                <div className="flex-1 overflow-y-auto p-4 space-y-3 custom-scrollbar">
                    {logs.map((log) => (
                    <div key={log.id} className="text-sm flex gap-3 items-start group">
                        <span className={`text-[10px] font-mono px-1.5 py-0.5 rounded border ${
                            log.type === 'WRN' ? 'border-orange-500/30 text-orange-400 bg-orange-500/10' : 
                            'border-blue-500/30 text-blue-400 bg-blue-500/10'
                        }`}>
                            {log.type}
                        </span>
                        <div className="flex-1">
                            <span className="text-slate-300 block text-xs group-hover:text-white transition-colors">{log.msg}</span>
                            <span className="text-[10px] text-slate-600 font-mono">{log.time}</span>
                        </div>
                    </div>
                    ))}
                </div>
            </div>

            {/* RUL Distribution (Uses Fallback from Static Data) */}
            <div className="bg-slate-800/30 p-4 rounded-2xl border border-white/5">
              <div className="flex items-center justify-between">
                <h4 className="text-white text-sm font-medium mb-2">Test Set Distribution</h4>
              </div>
              <div className="h-40">
                {rulDist && rulDist.length > 0 ? (
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={rulDist} margin={{ top: 4, right: 8, left: 0, bottom: 0 }}>
                      <XAxis dataKey="bin" hide />
                      <Tooltip 
                        contentStyle={{ backgroundColor: '#0f172a', borderColor: '#334155', fontSize: '12px' }}
                        cursor={{fill: '#334155', opacity: 0.2}} 
                      />
                      <Bar dataKey="count" fill="#06b6d4" radius={[2, 2, 0, 0]} />
                    </BarChart>
                  </ResponsiveContainer>
                ) : (
                  <div className="h-full flex items-center justify-center text-xs text-slate-500">
                    {loading ? "Calculating..." : "No distribution data"}
                  </div>
                )}
              </div>
              <p className="text-[10px] text-slate-500 mt-2">RUL values are capped at 120 hours in preprocessing; values beyond this horizon are shown at 120h.</p>
              {/* RUL over time */}
              <div className="mt-4 bg-slate-900/30 p-3 rounded">
                <h5 className="text-xs text-slate-300 mb-2">RUL over time</h5>
      <div className="h-36">
                  {staticData && (staticData.train_data || staticData.test_data) ? (
                    <ResponsiveContainer width="100%" height="100%">
                      <LineChart data={downsample([...(staticData.train_data || []), ...(staticData.test_data || [])], 1200)}>
                        <CartesianGrid strokeDasharray="3 3" stroke="#334155" vertical={false} opacity={0.2} />
                        <XAxis dataKey="time" hide />
        <YAxis stroke="#64748b" tick={{fontSize:10}} width={30} domain={[0,120]} />
                        <Tooltip contentStyle={{ backgroundColor: '#0f172a' }} />
                        <Line type="monotone" dataKey="Actual" stroke="#64748b" strokeWidth={2} dot={false} />
                      </LineChart>
                    </ResponsiveContainer>
                  ) : rulSeries && rulSeries.length > 0 ? (
                    <ResponsiveContainer width="100%" height="100%">
                      <LineChart data={rulSeries.map((r: any) => ({ x: r.index, rul: r.rul }))}>
                        <CartesianGrid strokeDasharray="3 3" stroke="#334155" vertical={false} opacity={0.2} />
                        <XAxis dataKey="x" hide />
        <YAxis stroke="#64748b" tick={{fontSize:10}} width={30} domain={[0,120]} />
                        <Tooltip contentStyle={{ backgroundColor: '#0f172a' }} />
                        <Line type="monotone" dataKey="rul" stroke="#64748b" strokeWidth={2} dot={false} />
                      </LineChart>
                    </ResponsiveContainer>
                  ) : (
                    <div className="h-full flex items-center justify-center text-xs text-slate-500">No time-series available</div>
                  )}
                </div>
              </div>
            </div>
        </div>

      </div>
    </div>
  );
}

export default Overview;